### ISSUE TITLE
Merge or link https://github.com/urmet/esteid-overlay

### ISSUE THREAD

**Issue by sainsaar** [open-eid/gentoo#1]
There is a Gentoo overlay at https://github.com/urmet/esteid-overlay containing all the necessary software for Estonian ID-card to work. Perhaps you could either pull it here or at least link to it? That repository was last updated in September, and thus is a bit outdated (although working), but copying the ebuilds for their names to point to the latest versions worked well.

**Comment by martinpaljak** [comment]
Huh-hoh. No Gentoo users here. Especially if you say that it requires modifications for the latest versions etc, could you please make a full PR? The repository was created because we had some interest from the community to provide something but that faded away...

**Comment by urmet** [comment]
Yeah. There was enough activism to create this repo but not enough to actually fix my stuff so it could be shown here as "official". Send me some patches/PR's @sainsaar and lets make it happen :)

**Comment by urmet** [comment]
I bumped package versions in my repo. Browser stuff is missing/broken but everything else seems to build and work fine. If there's nothing too wrong with it(someone please take a look :) I could push it here.

**Comment by sainsaar** [comment]
Hmm, for me "the browser stuff" worked... I'll take a look at it.

**Comment by urmet** [comment]
Oh yea. The authentication part seems to work. Then it was the signing part that caused me trouble.

**Comment by lkraav** [comment]
Yeah I can confirm, I've successfully authenticated for a long while now, but can't recall signing. Been using mID a lot now to overcome this problem.

**Comment by sainsaar** [comment]
I've merged in a working signing plugin for Firefox by now. It really was missing from urmet's repository.
