### ISSUE TITLE
Cannot find file 'EE.xml'

### ISSUE THREAD

**Issue by monoidic** [open-eid/gentoo#18]
Ei tea, mis keeles siin rääkima peaks...
While trying to compile qdigidoc via either the -3.13.5 or -9999 ebuild, it hits an error at "Generating qrc_TSL.cpp"
```sh
cd /var/tmp/portage/app-crypt/qdigidoc-9999/work/qdigidoc-9999_build/client && /usr/lib64/qt5/bin/rcc --name TSL --output /var/tmp/portage/app-crypt/qdigidoc-9999/work/qdigidoc-9999_build/client/qrc_TSL.cpp /var/tmp/portage/app-crypt/qdigidoc-9999/work/qdigidoc-9999_build/client/TSL.qrc
RCC: Error in '/var/tmp/portage/app-crypt/qdigidoc-9999/work/qdigidoc-9999_build/client/TSL.qrc':
Cannot find file 'EE.xml'
```

While checking through the build log, I found a reference to EE.xml at "Generating TSL.qrc, tl-mp.xml, EE.xml", which does this:
```sh
cd /usr/bin && /var/tmp/portage/app-crypt/qdigidoc-9999/work/qdigidoc-9999_build/client/TSLDownload /var/tmp/portage/app-crypt/qdigidoc-9999/work/qdigidoc-9999_build/client EE
```
After checking ```/var/tmp/portage/app-crypt/qdigidoc-9999/work/qdigidoc-9999_build/client```, I found that it wasn't there. After running that command manually, though, the file EE.xml appears there.

I tried unsetting some FEATURES like fakeroot, userpriv andusersandbox and setting -j1 in case they were interfering, but it didn't change anything. I'm guessing it just failed because Portage sandboxing didn't allow it to cd to /usr/bin and therefore the TSLDownload didn't run in the first place.
Using the same sources from the distfiles and ```mkdir build && cd build && cmake .. && make -j6``` worked, so it has to be Portage.

**Comment by monoidic** [comment]
It seems like the FEATURE network-sandbox is set by default, which interferes with TSLdownload. Maybe this should be mentioned somewhere.

Also, this can be fixed by adding "app-crypt/qdigidoc no_network_sandboxing" to `/etc/portage/package.env` and making a file named `no_network_sandboxing` in `/etc/portage/env` containing `FEATURES="${FEATURES} -network-sandbox"`

**Comment by metsma** [comment]
https://github.com/open-eid/qdigidoc/wiki/DeveloperTips#building-in-sandboxed-environment
https://github.com/open-eid/qesteidutil/wiki/DeveloperTips#building-in-sandboxed-environment

**Comment by monoidic** [comment]
Oh. Well, this can be fixed with [some](https://w1r3.net/xWgxWk.txt) massive [patches](https://w1r3.net/kjbmYX.txt) (at least for qdigidoc, since tl-mp.xml and EE.xml are around half a megabyte in total), but since this data seems to be meant to be fetched at build time, it seems like it's supposed to be relatively up to date, so adding a patch to include those files may not be a good idea.
