### ISSUE TITLE
ERROR: app-crypt/qesteidutil-3.12.10::esteid failed (depend phase): External commands disallowed while sourcing ebuild: replace_version_separator _ -

### ISSUE THREAD

**Issue by lkraav** [open-eid/gentoo#19]

**Comment by h4evik** [comment]
Suggested patch:

--- ./a/qesteidutil-3.12.10.ebuild	2018-05-28 21:56:58.624518828 +0300
+++ ./b/qesteidutil-3.12.10.ebuild	2018-05-28 21:57:37.051038430 +0300
@@ -3,7 +3,7 @@
 
 EAPI="5"
 
-inherit cmake-utils flag-o-matic
+inherit cmake-utils flag-o-matic versionator
 
 DESCRIPTION="ID-card utility"
 HOMEPAGE="https://github.com/open-eid/qesteidutil"
