### ISSUE TITLE
Adding repo in Gentoo

### ISSUE THREAD

**Issue by h4evik** [open-eid/gentoo#2]
To add Esteid repo into layman just run command:

layman -o https://raw.githubusercontent.com/open-eid/gentoo/master/profiles/overlay.xml -f -a esteid

**Comment by urmet** [comment]
-f flag is deprecated, -o and -a will only effect the current execution of the command. Current instructions work fine and don't cause any warnings/errors.

**Comment by urmet** [comment]
`layman -s esteid` output with proposed change

> - Warnings:
> - ------
> - Overlay "esteid" could not be found in the remote lists.
> - Please check if it has been renamed and re-add if necessary.
>   *

**Comment by h4evik** [comment]
Yep, but before were:

> - Fetching remote list...
>   - Fetch Ok
>   - Syncing selected overlay(s)...
>   - Running Git... # ( cd /var/lib/layman/esteid  && /usr/bin/git pull )
>     Already up-to-date.
>   - 
>   - Succeeded:
>   - ------
>   - Successfully synchronized overlay "esteid".
>   - 

Am I right?
