### ISSUE TITLE
app-crypt/qdigidoc4: missing DEPEND net-nds/openldap?

### ISSUE THREAD

**Issue by lkraav** [open-eid/gentoo#42]
My binpkg host has openldap, and qdigidoc4 seems to build against it.

https://github.com/open-eid/DigiDoc4-Client/blob/v4.2.4/CMakeLists.txt#L20 does say `find_package( LDAP REQUIRED )`

But our ebuild doesn't say anything about LDAP. Should it?

This is creating a problem on client hosts without openldap installed. Wondering if I can avoid it, ideally it'd be a USE flag. I'm not even sure what qdigidoc4 uses LDAP for?

**Comment by martinpaljak** [comment]
For acquiring recipient certificates when using encryption.

**Comment by lkraav** [comment]
Sounds like `net-nds/openldap[minimal]` might be appropriate?

**Comment by urmet** [comment]
sounds reasonable.
I'll take a look at the outstanding issues and updates during the weekend.

**Comment by lkraav** [comment]
Any luck here @urmet?
