### ISSUE TITLE
libdigidoc-3.10.5.ebuild depends on deprecated eapi 7 and cmake-utils eclass

### ISSUE THREAD

**Issue by mattiasMerilai** [open-eid/gentoo#52]
libdigidoc-3.10.5.ebuild uses deprecated eapi 6 and cmake-utils eclass, leading portage to complain upon seeing the file and failing to build.
Bumping eapi to 7 and replacing cmake-utils with cmake eclass leads to a successful build, albeit with qa warnings. My limited testing seems to indicate that I did not break anything, but I have no idea what to look for, nor the skills to do so either, so I guess someone who knows what they are doing should take a look:)

[libdigidoc-3.10.5.patch.txt](https://github.com/open-eid/gentoo/files/9249681/libdigidoc-3.10.5.patch.txt)
.

**Comment by metsma** [comment]
This package is obsolete and recent libdigidocpp does not depend/use it

**Comment by mattiasMerilai** [comment]
So we would need an ebuild for such a recent libdigidocpp?

**Comment by metsma** [comment]
libdigidocpp 3.14.8 is recent enough. Latest is 3.14.10

**Comment by jaakristioja** [comment]
> This package is obsolete and recent libdigidocpp does not depend/use it

However, the obsolete package is still in the overlay and causes `emerge` to complain every time it parses the ebuild, e.g. even during regular `@world` upgrades.

I also fixed this in https://github.com/jaakristioja/open-eid-gentoo similarly to the patch introduced by @MattiasMerilai, but did not yet submit it as a merge request. I originally thought about trying to fix all `pkgcheck scan` errors/warnings before submitting it, but now I think I don't have enough free time and motivation to finish this work in the short term. Please feel free to merge or cherry-pick any of my changes, if this helps.

**Comment by mattiasMerilai** [comment]
Drop libdigidoc dependency, and additionally, drop openssl-1.1.1m-compat.patch for 3.14.10

[libdigidocpp-3.14.8-r1.ebuild.txt](https://github.com/open-eid/gentoo/files/9251037/libdigidocpp-3.14.8-r1.ebuild.txt)
[libdigidocpp-3.14.10.ebuild.txt](https://github.com/open-eid/gentoo/files/9251038/libdigidocpp-3.14.10.ebuild.txt)

**Comment by urmet** [comment]
I merged in the eapi changes from @jaakristioja fork. I'll try to get some updates and cleanups done this weekend or start of next week.
