### ISSUE TITLE
didn't work until I installed native ccid and pcsc-lite pcscd daemon

### ISSUE THREAD

**Issue by articice** [open-eid/gentoo#9]
Hi!

I have connected the repository and emerged both www-plugins, but they refused to work.
Then, I started poking the opensc-explorer and other commands, all of them said that no card readers were found (card reader was visible under lsusb).

Then, I installed native ccid and pcsc-lite and started the pcscd daemon with 
```
sudo pcscd -a -d -f
```
after re-inserting the card it worked.

Is this a dependency problem in www-plugins?

I think it needs the daemon from pcsc-lite to work, so
* pcsc-lite USE flag for opensc should be required by these packages

**Comment by martinpaljak** [comment]
Both are necessary requirements for (almost all) software from open-eid group. CCID could be replaced by a proprietary driver, but for 99% of cases CCID is the right thing.

The Gentoo repository is community-maintained, please fire up pull requests if possible.

**Comment by articice** [comment]
Ok, will do so after some more testing.

**Comment by urmet** [comment]
seems done
